# InstructGS Configuration File
# Text-guided 3D scene editing with Gaussian Splatting

# Experiment Configuration
experiment:
  name: "instruct_gs_experiment"
  description: "Text-guided 3D scene editing"
  output_dir: "outputs"
  resume_from: null  # Path to checkpoint to resume from
  
# Dataset Configuration  
data:
  data_dir: "datasets/360_v2/garden"
  data_factor: 4              # Image downsampling factor (1, 2, 4, 8)
  test_every: 8               # Every Nth image for validation
  normalize_world_space: true
  
# InstructGS Editing Configuration
editing:
  edit_prompt: "Turn it into a beautiful oil painting"
  edit_mode: "restyle"        # Options: replace, remove, restyle
  cycle_steps: 2500           # 3DGS optimization steps per round
  max_rounds: 10              # Maximum editing rounds
  views_per_round: 8          # Number of views to edit per round (0 = all views)
  coverage_threshold: 0.1     # Minimum RoI coverage for view selection
  
# 2D Diffusion Model Configuration
diffusion:
  model_name: "timbrooks/instruct-pix2pix"
  device: "cuda"              # Device for InstructPix2Pix
  steps: 20                   # Diffusion denoising steps
  guidance_scale: 7.5         # CFG guidance strength
  image_guidance_scale: 1.5   # Image guidance strength
  seed: 42                    # Random seed for reproducibility
  
# 3D Gaussian Splatting Configuration
gaussian:
  init_type: "sfm"            # Initialization: sfm, random
  init_num_pts: 100000        # Number of initial points (if random)
  init_extent: 3.0            # Scene extent for random init
  init_opacity: 0.1           # Initial opacity
  init_scale: 1.0             # Initial scale multiplier
  sh_degree: 3                # Spherical harmonics degree
  
# Optimization Configuration
optimization:
  # Learning rates
  means_lr: 0.00016
  scales_lr: 0.005
  opacities_lr: 0.05
  quats_lr: 0.001
  sh0_lr: 0.0025
  shN_lr: 0.000125
  
  # Densification strategy
  strategy: "default"         # default, mcmc
  prune_opa: 0.005           # Opacity threshold for pruning
  grow_grad2d: 0.0002        # 2D gradient threshold for densification
  grow_scale3d: 0.01         # 3D scale threshold for densification
  prune_scale3d: 0.1         # 3D scale threshold for pruning
  refine_start_iter: 500     # Start densification at iteration
  refine_stop_iter: 15000    # Stop densification at iteration
  refine_every: 100          # Densification frequency
  reset_every: 3000          # Reset opacity frequency
  
# Loss Configuration
losses:
  photometric_weight: 1.0     # Weight for photometric loss in RoI
  preservation_weight: 0.5    # Weight for preservation loss outside RoI
  consistency_weight: 0.1     # Weight for cross-view consistency
  perceptual_weight: 0.0      # Weight for perceptual loss (LPIPS)
  depth_weight: 0.0           # Weight for depth loss
  
# Region of Interest Configuration
roi:
  mask_type: "automatic"      # automatic, manual, prompt
  mask_prompt: null           # Text prompt for automatic masking
  mask_threshold: 0.5         # Threshold for automatic masking
  mask_dilation: 5            # Dilation for mask edges
  
# Evaluation Configuration
evaluation:
  eval_every: 5               # Evaluate every N rounds
  save_renders: true          # Save rendered images
  save_metrics: true          # Save quantitative metrics
  compute_lpips: true         # Compute LPIPS metric
  compute_clip: false         # Compute CLIP similarity
  
# System Configuration
system:
  device: "cuda"
  num_workers: 4
  pin_memory: true
  mixed_precision: true
  seed: 42
  
# Logging Configuration
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  log_every: 10               # Log every N iterations within round
  tensorboard: true           # Enable tensorboard logging
  wandb: false                # Enable Weights & Biases logging
  save_images_every: 1        # Save images every N rounds
  
# Path Configuration
paths:
  checkpoints: "checkpoints"
  renders: "renders" 
  logs: "logs"
  metrics: "metrics"
  artifacts: "artifacts"